### ISSUE TITLE
Getting N/A for Cluser File system Usage

### ISSUE THREAD

**Issue by gaya3chandran1** [instrumentisto/grafana-dashboard-kubernetes-prometheus#5]
I am getting N/A for Cluser File system Usage. I understand that this has to be edited device=~"^/dev/[vs]da9$" but i could not figure out where this change has to be mafe.

**Comment by gaya3chandran1** [comment]
I understand this line has to be changed in the json
"expr": "sum (container_fs_limit_bytes{device=~\"^/dev/[sv]da9$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})",

say my devices are 10.11.12.133, 10.11.12.134 how should I get them added.

**Comment by tyranron** [comment]
@gaya3chandran1 do you have CoreOS bare metal Kubernetes installation?

If yes, then run `df -h` on any node and give me output.

If no, then explain how exactly your Kubernetes cluster is installed. Maybe, this dashboard won't suite you.

**Comment by gaya3chandran1** [comment]
Linux version
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.1.1503 (Core)
Release:        7.1.1503
Codename:       Core

0(root@ddaikbt01 /home/teln)$ df -h
Filesystem                        Size  Used Avail Use% Mounted on
/dev/xvda1                         30G  4.8G   26G  16% /
devtmpfs                          7.8G     0  7.8G   0% /dev
none                              1.0G     0  1.0G   0% /dev/shm
tmpfs                             7.7G  787M  6.9G  11% /run
tmpfs                             7.7G     0  7.7G   0% /sys/fs/cgroup
/dev/xvdf                         100G   23G   78G  23% /DATA
/dev/mapper/vgroot-home            20G   59M   20G   1% /home
/dev/mapper/vgroot-tmp             20G   35M   20G   1% /tmp
/dev/mapper/vgroot-var             20G  4.2G   16G  21% /var
/dev/mapper/vgroot-var_log         20G  550M   20G   3% /var/log
/dev/mapper/vgroot-var_tmp        5.0G  479M  4.6G  10% /var/tmp
/dev/mapper/vgroot-var_log_audit  5.0G  1.8G  3.3G  35% /var/log/audit
10.43.36.211:/                    8.0E  488M  8.0E   1% /EFS
tmpfs                             7.7G   12K  7.7G   1%
/var/lib/kubelet/pods/503c1b85-836e-11e7-8c73-12b16417eb5a/volumes/
kubernetes.io~secret/weave-net-token-jl188
overlay                           100G   23G   78G  23%
/DATA/docker/overlay/3e909ac233d4e4de36a2ccfe2d90096dc7ac67b992e7cac1a7c7e76d90d972e0/merged
shm                                64M     0   64M   0%
/DATA/docker/containers/e0418dbcf04287628c116fd592c56858cc2d7ed56e4c7c55c750f83d36934b49/shm
tmpfs                             7.7G   12K  7.7G   1%
/var/lib/kubelet/pods/6b95a843-9c8d-11e7-a8fe-12b16417eb5a/volumes/
kubernetes.io~secret/default-token-jp6zv
overlay                           100G   23G   78G  23%
/DATA/docker/overlay/61446c8caba5941e4159cd06ae4752389ca28ca1951c8162ad99baf6508c49e8/merged
shm                                64M     0   64M   0%
/DATA/docker/containers/3b8292603dc0bf7a77bdae5fc252375fbf5b6b45c38a6427cd4cc3c4bb0ffc70/shm
overlay                           100G   23G   78G  23%
/DATA/docker/overlay/327847406c1d622a34d3781c34ab6fc6ce87a040f908d7f37317

**Comment by tyranron** [comment]
@gaya3chandran1 yup... you're using CentOS (not CoreOS).

This dashboard was never designed and tested for CentOS, so it's up yo you to tweak its parameters to make it work.

As for disk devices, you should specify 
```
"expr": "sum (container_fs_limit_bytes{device="^/dev/xvda1$",id="/",kubernetes_io_hostname="^$Node$"})",
```
to make it work... I guess...

The `/dev/xvda1` device is where your root filesystem located. But I also see that you have `/dev/xvdf` mounted to your data `/DATA`. If you want to count that too in your dashboard, use
```
"expr": "sum (container_fs_limit_bytes{device="^/dev/xvda1?$",id="/",kubernetes_io_hostname="^$Node$"})",
```

**Comment by vasili439** [comment]
I changed device name to device=~"^/dev/[hsvx]{1,2}d[a-z][1-9]$" to be compatible with amazon ebs and hdX drives
