### ISSUE TITLE
support for kuberenetes 1.8+

### ISSUE THREAD

**Issue by V3ckt0r** [instrumentisto/grafana-dashboard-kubernetes-prometheus#7]
Hey guys,

This dashboard doesn't seem to work for k8s version 1.8 and up.

The queries need to be change to make use of the metric changes.

Please see gist [here](https://gist.github.com/V3ckt0r/c708506955f65a2e5b78688fa04387c2) showing the latest prometheus telementry metrics that k8s provides

**Comment by tyranron** [comment]
@V3ckt0r you've linked to metrics of `kube-apiserver`. This dashboard does not use them. It uses only `kubelet` metrics (received from built-in `cAdvisor`).

We're running OK this dashboard with latest stable Kubernetes (`1.9.3` at the moment).

Which metrics exactly doesn't work in you case?

**Comment by V3ckt0r** [comment]
thanks @tyranron,

I thought I had added new cAdvisor endpoint but it turns out I didn't! 😄 

https://github.com/prometheus/prometheus/pull/2918
