### ISSUE TITLE
Node drop down menu missing node names

### ISSUE THREAD

**Issue by cloudoutloud** [instrumentisto/grafana-dashboard-kubernetes-prometheus#8]
This was working initially, but all of a sudden disappeared.
Tried re importing dashboard. I can only view all metrics now not specific nodes.  

![image](https://user-images.githubusercontent.com/39462069/62212679-298d3900-b399-11e9-98b0-165c3677943e.png)

**Comment by cloudoutloud** [comment]
@targs08 any update with this?

**Comment by targs08** [comment]
@cloudoutloud, this dashboard use [`kubernetes.io/hostname` label](https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#kubernetes-io-hostname) for grouping node's metrics. [Reference](https://github.com/instrumentisto/grafana-dashboard-kubernetes-prometheus/blob/master/dashboard.json#L2065)

Make sure nodes have this label and Prometheus has relevant data.

**Comment by cloudoutloud** [comment]
All nodes have that label.
Was working on initial set up, there has been no config change to node or Prometheus deployment. Odd it has just disappeared..
